gatekeeper:
  enabled: false
twistlock:
  enabled: false
logging:
  enabled: false
jaeger:
  enabled: false
eckoperator:
  enabled: false
clusterAuditor:
  enabled: false
fluentbit:
  enabled: false
monitoring:
  enabled: true
  values:
    alertmanager:
      enabled: false
istio:
  values:
    gateways:
      ssh:
        selector:
          app: public-ingressgateway
        servers:
        - hosts:
          - 'ssh.bigbang.dev'
          port:
            number: 2222
            name: tcp-ssh
            protocol: TCP
      vnc:
        selector:
          app: public-ingressgateway
        servers:
        - hosts:
          - 'vnc.bigbang.dev'
          port:
            name: tcp-vnc
            number: 5904
            protocol: TCP
    ingressGateways:
      public-ingressgateway:
        k8s:
          service:
            ports:
              - name: vnc
                port: 5904
                targetPort: 5904
              - name: status-port
                port: 15021
              - name: http2
                port: 80
                targetPort: 8080
              - name: https
                port: 443
                targetPort: 8443
              - name: ssh
                port: 2222
                targetPort: 2222