---
apiVersion: v1
kind: Service
metadata:
  name: istio-vmi-svc
  namespace: istio-vmi
spec:
  selector:
    app: istio-vmi-tom
  ports:
  - port: 8080
    name: server
    protocol: TCP
  - port: 9090
    name: cockpit
    protocol: TCP
  - port: 5904
    name: vnc
    protocol: TCP
  - port: 22
    name: ssh
    protocol: TCP