apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: kubevirt
  namespace: kubevirt
spec:
  gateways:
  - istio-system/public
  hosts:
  - kubevirt.bigbang.dev
  http:
  - route:
    - destination:
        host: istio-vmi-svc.istio-vmi.svc.cluster.local
        port:
          number: 8080
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: cockpit
  namespace: kubevirt
spec:
  gateways:
  - istio-system/public
  hosts:
  - cockpit.bigbang.dev
  http:
  - route:
    - destination:
        host: istio-vmi-svc.istio-vmi.svc.cluster.local
        port:
          number: 9090
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: kubevirt
  namespace: kubevirt
spec:
  gateways:
  - istio-system/public
  hosts:
  - ssh.bigbang.dev
  http:
  - route:
    - destination:
        host: istio-vmi-svc.istio-vmi.svc.cluster.local
        port:
          number: 22
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: kubevirt
  namespace: kubevirt
spec:
  gateways:
  - istio-system/public
  hosts:
  - vnc.bigbang.dev
  http:
  - route:
    - destination:
        host: istio-vmi-svc.istio-vmi.svc.cluster.local
        port:
          number: 5904