apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: kubevirt
  namespace: kubevirt
spec:
  gateways:
  - istio-system/public
  hosts:
  - kubevirt.bigbang.dev
  http:
  - route:
    - destination:
        host: virt-api.kubevirt.svc.cluster.local
        port:
          number: 443